//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the eppacher_hw2 package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __eppacher_hw2__DYNAMIC_RECONFIGURE_PARAM_2CONFIG_H__
#define __eppacher_hw2__DYNAMIC_RECONFIGURE_PARAM_2CONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace eppacher_hw2
{
  class dynamic_reconfigure_param_2ConfigStatics;

  class dynamic_reconfigure_param_2Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(dynamic_reconfigure_param_2Config &config, const dynamic_reconfigure_param_2Config &max, const dynamic_reconfigure_param_2Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const dynamic_reconfigure_param_2Config &config1, const dynamic_reconfigure_param_2Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, dynamic_reconfigure_param_2Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const dynamic_reconfigure_param_2Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dynamic_reconfigure_param_2Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const dynamic_reconfigure_param_2Config &config) const = 0;
      virtual void getValue(const dynamic_reconfigure_param_2Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T dynamic_reconfigure_param_2Config::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T dynamic_reconfigure_param_2Config::* field;

      virtual void clamp(dynamic_reconfigure_param_2Config &config, const dynamic_reconfigure_param_2Config &max, const dynamic_reconfigure_param_2Config &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const dynamic_reconfigure_param_2Config &config1, const dynamic_reconfigure_param_2Config &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, dynamic_reconfigure_param_2Config &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const dynamic_reconfigure_param_2Config &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dynamic_reconfigure_param_2Config &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const dynamic_reconfigure_param_2Config &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const dynamic_reconfigure_param_2Config &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, dynamic_reconfigure_param_2Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, dynamic_reconfigure_param_2Config &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<dynamic_reconfigure_param_2Config::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(dynamic_reconfigure_param_2Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("x_param_1"==(*_i)->name){x_param_1 = boost::any_cast<double>(val);}
        if("y_param_1"==(*_i)->name){y_param_1 = boost::any_cast<double>(val);}
        if("theta_goal_param_1"==(*_i)->name){theta_goal_param_1 = boost::any_cast<int>(val);}
        if("x_param_2"==(*_i)->name){x_param_2 = boost::any_cast<double>(val);}
        if("y_param_2"==(*_i)->name){y_param_2 = boost::any_cast<double>(val);}
        if("theta_goal_param_2"==(*_i)->name){theta_goal_param_2 = boost::any_cast<int>(val);}
        if("x_param_3"==(*_i)->name){x_param_3 = boost::any_cast<double>(val);}
        if("y_param_3"==(*_i)->name){y_param_3 = boost::any_cast<double>(val);}
        if("theta_goal_param_3"==(*_i)->name){theta_goal_param_3 = boost::any_cast<int>(val);}
        if("x_param_4"==(*_i)->name){x_param_4 = boost::any_cast<double>(val);}
        if("y_param_4"==(*_i)->name){y_param_4 = boost::any_cast<double>(val);}
        if("theta_goal_param_4"==(*_i)->name){theta_goal_param_4 = boost::any_cast<int>(val);}
        if("rho_param"==(*_i)->name){rho_param = boost::any_cast<double>(val);}
        if("alpha_param"==(*_i)->name){alpha_param = boost::any_cast<double>(val);}
        if("beta_param"==(*_i)->name){beta_param = boost::any_cast<double>(val);}
        if("turn_on_turn_off"==(*_i)->name){turn_on_turn_off = boost::any_cast<bool>(val);}
      }
    }

    double x_param_1;
double y_param_1;
int theta_goal_param_1;
double x_param_2;
double y_param_2;
int theta_goal_param_2;
double x_param_3;
double y_param_3;
int theta_goal_param_3;
double x_param_4;
double y_param_4;
int theta_goal_param_4;
double rho_param;
double alpha_param;
double beta_param;
bool turn_on_turn_off;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_param_1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_param_1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int theta_goal_param_1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_param_2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_param_2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int theta_goal_param_2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_param_3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_param_3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int theta_goal_param_3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double x_param_4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double y_param_4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int theta_goal_param_4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rho_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double alpha_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double beta_param;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool turn_on_turn_off;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("dynamic_reconfigure_param_2Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const dynamic_reconfigure_param_2Config &__max__ = __getMax__();
      const dynamic_reconfigure_param_2Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const dynamic_reconfigure_param_2Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const dynamic_reconfigure_param_2Config &__getDefault__();
    static const dynamic_reconfigure_param_2Config &__getMax__();
    static const dynamic_reconfigure_param_2Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const dynamic_reconfigure_param_2ConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void dynamic_reconfigure_param_2Config::ParamDescription<std::string>::clamp(dynamic_reconfigure_param_2Config &config, const dynamic_reconfigure_param_2Config &max, const dynamic_reconfigure_param_2Config &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class dynamic_reconfigure_param_2ConfigStatics
  {
    friend class dynamic_reconfigure_param_2Config;

    dynamic_reconfigure_param_2ConfigStatics()
    {
dynamic_reconfigure_param_2Config::GroupDescription<dynamic_reconfigure_param_2Config::DEFAULT, dynamic_reconfigure_param_2Config> Default("Default", "", 0, 0, true, &dynamic_reconfigure_param_2Config::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_param_1 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_param_1 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_param_1 = 4.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_1", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_1", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_param_1 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_param_1 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_param_1 = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_1", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_1", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.theta_goal_param_1 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.theta_goal_param_1 = 360;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.theta_goal_param_1 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_1", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_1", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_1)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_param_2 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_param_2 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_param_2 = 6.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_2", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_2", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_param_2 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_param_2 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_param_2 = -2.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_2", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_2", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.theta_goal_param_2 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.theta_goal_param_2 = 360;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.theta_goal_param_2 = 270;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_2", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_2", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_2)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_param_3 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_param_3 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_param_3 = 4.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_3", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_3", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_param_3 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_param_3 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_param_3 = -4.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_3", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_3", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.theta_goal_param_3 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.theta_goal_param_3 = 360;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.theta_goal_param_3 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_3", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_3", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_3)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.x_param_4 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.x_param_4 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.x_param_4 = 4.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_4", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("x_param_4", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::x_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.y_param_4 = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.y_param_4 = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.y_param_4 = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_4", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("y_param_4", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::y_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.theta_goal_param_4 = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.theta_goal_param_4 = 360;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.theta_goal_param_4 = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_4", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<int>("theta_goal_param_4", "int", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::theta_goal_param_4)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rho_param = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rho_param = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rho_param = 0.01;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("rho_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::rho_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("rho_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::rho_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.alpha_param = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.alpha_param = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.alpha_param = 0.3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("alpha_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::alpha_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("alpha_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::alpha_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.beta_param = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.beta_param = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.beta_param = 0.1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("beta_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::beta_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<double>("beta_param", "double", 0, "A double parameter", "", &dynamic_reconfigure_param_2Config::beta_param)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.turn_on_turn_off = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.turn_on_turn_off = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.turn_on_turn_off = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<bool>("turn_on_turn_off", "bool", 0, "A Boolean parameter", "", &dynamic_reconfigure_param_2Config::turn_on_turn_off)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr(new dynamic_reconfigure_param_2Config::ParamDescription<bool>("turn_on_turn_off", "bool", 0, "A Boolean parameter", "", &dynamic_reconfigure_param_2Config::turn_on_turn_off)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(dynamic_reconfigure_param_2Config::AbstractGroupDescriptionConstPtr(new dynamic_reconfigure_param_2Config::GroupDescription<dynamic_reconfigure_param_2Config::DEFAULT, dynamic_reconfigure_param_2Config>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<dynamic_reconfigure_param_2Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<dynamic_reconfigure_param_2Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    dynamic_reconfigure_param_2Config __max__;
    dynamic_reconfigure_param_2Config __min__;
    dynamic_reconfigure_param_2Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const dynamic_reconfigure_param_2ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static dynamic_reconfigure_param_2ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &dynamic_reconfigure_param_2Config::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const dynamic_reconfigure_param_2Config &dynamic_reconfigure_param_2Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const dynamic_reconfigure_param_2Config &dynamic_reconfigure_param_2Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const dynamic_reconfigure_param_2Config &dynamic_reconfigure_param_2Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<dynamic_reconfigure_param_2Config::AbstractParamDescriptionConstPtr> &dynamic_reconfigure_param_2Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<dynamic_reconfigure_param_2Config::AbstractGroupDescriptionConstPtr> &dynamic_reconfigure_param_2Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const dynamic_reconfigure_param_2ConfigStatics *dynamic_reconfigure_param_2Config::__get_statics__()
  {
    const static dynamic_reconfigure_param_2ConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = dynamic_reconfigure_param_2ConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DYNAMIC_RECONFIGURE_PARAM_2RECONFIGURATOR_H__
